### ISSUE TITLE
'obtain_azure_instance_for' loop

### ISSUE THREAD

**Issue by mrpatiwi** [supportify/paperclip-azure#1]
I was using your gem and i noticed it took several minutes to upload a small image.
It seems that on `azure.rb` file, inside the loop, it keeps trying to find a valid filter even after getting a valid one (you can verify this checking the status code response (200)). I just replaced:
`sleep (retry_data[:count] - 1) * 5 ` with `next` and everything is working good. Line 152.

**Comment by jordanyaker** [comment]
Thanks for logging this.  I based the retry policy on some of the code from the .NET library.  Because their code works, 200 responses don't hit their retry policy code.  I added the check in commit a084dbdd3e24b45e4d4e2a998e9217a2c013c10f.  Let me know if you run in to any other issues.
