### ISSUE TITLE
Can't config (return 403 unauthorized)

### ISSUE THREAD

**Issue by antprt** [supportify/paperclip-azure#10]
I have the same configuration that in the documentation, but when I'm going to upload a file the server return 403error.

Can someone write a complete example?

I initialized in my production.rb file and I pass other options of paperclip as size (small) or validations in the model.

**Comment by jordanyaker** [comment]
@antprt are you still having this issue?

**Comment by antprt** [comment]
I returned to S3 and paperclip. It was imposible to salve the error.

I read that carrierwave gem support azure but do not try.

**Comment by jordanyaker** [comment]
@antprt my apologies.  Best of luck to you!

**Comment by jordanyaker** [comment]
Confirmed working as of 21da90f.
