### ISSUE TITLE
paperclip-azure should specify azure gem version

### ISSUE THREAD

**Issue by atomanyih** [supportify/paperclip-azure#11]
the `azure >= 0.0.0` version requirement seems to cause bundler to install the `azure` gem at version 0.0.0

version 0.0.0 exists but is empty, causing this other issue: https://github.com/supportify/paperclip-azure/issues/9

making the version more specific would prevent this. even `> 0.0.0` would work, but it wouldn't hurt to figure out the version we actually need

**Comment by jordanyaker** [comment]
@atomanyih I'm going to be spending the next day or so updating and refactoring the gem.  This is one of the items that I will be tackling.

**Comment by jordanyaker** [comment]
Fixed in 21da90f.
