### ISSUE TITLE
Not working with Ruby 2.3.0

### ISSUE THREAD

**Issue by eduardm** [supportify/paperclip-azure#7]
"can't modify frozen String" 
error is triggered when trying to save an object that has_attached_file with storage: :azure.
After some checking seems that the issue is located in blob_service.rb in line 1382 from Azure gem.

headers['Content-Encoding'].downcase! -> this does not work anymore in Ruby 2.3.0. For more info: https://bugs.ruby-lang.org/issues/11473 

Fix is simple:
headers['Content-Encoding'] = headers['Content-Encoding'].downcase

Later edit:
This is already fixed in azure gem, in this commit:
https://github.com/Azure/azure-sdk-for-ruby/commit/1f13d7b87d7d9ed1ecd9e602d215cba8975d46ff

However, the gem version was not bumped after fix, so whoever has the gem installed before the fix, can't use it with Ruby 2.3, even with bundle update.

**Comment by jordanyaker** [comment]
@eduardm I am bumping the version of the Azure gem.  This should resolve the issue.

**Comment by jordanyaker** [comment]
Fixed in 21da90f.
