### ISSUE TITLE
paperclip-azure.rb:1:in `require': cannot load such file -- azure (LoadError)

### ISSUE THREAD

**Issue by antprt** [supportify/paperclip-azure#9]
I can't load the gem. When I up the server with the commando rails s launch the error: 

paperclip-azure.rb:1:in `require': cannot load such file -- azure (LoadError)

What should I do?

**Comment by antprt** [comment]
Solved myself.

I was the gem mime-types with higher version.

Solved puts in Gemfile azure > 0.0.0 and with bundle upgrade mime-types.

**Comment by smittix6** [comment]
I get this same error - not sure how to resolve. I'm using the latest version of the azure gem, paperclip 5.0.0, mime-types 3.1.

Any ideas?

**Comment by smittix6** [comment]
Running bundle update seems to have fixed it...

**Comment by atomanyih** [comment]
also having this problem, bundler says it installed `azure 0.0.0`

maybe `paperclip-azure` should ask for a more specific `azure` version?

**Comment by jordanyaker** [comment]
@smittix6 @antprt I started working on this gem for the first time in a while.  I will ensure that this gets resolved.

**Comment by jordanyaker** [comment]
Fixed in 21da90f.
